name = "zx_calculus"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZxCalculus"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "d62eab0cc36ea522904895389c301cf8d844fd69" 

[[lean_lib]]
name = "ZxCalculus"

[[lean_lib]]
name = "tests"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "9cfe6f912bbb5ce5ad1e06d1b58a30bddae82e63"

[[require]]
name = "quantumInfo"
git = "https://github.com/Timeroot/Lean-QuantumInfo.git"
rev = "7304e98727a411c246899f361b77ca529b31c9a8"