name = "zx_calculus"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZxCalculus"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "d62eab0cc36ea522904895389c301cf8d844fd69" 

[[lean_lib]]
name = "ZxCalculus"

[[lean_lib]]
name = "tests"